version: '3.8'
services:

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passw0rd
